include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
    file_names: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false