name: kuwot_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  dart_frog_auth: ^1.1.0
  encrypt: ^5.0.3
  envied: ^0.5.4+1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  pointycastle: ^3.9.1
  sqlite3: ^2.4.6
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^6.0.0
