@baseUrl = http://localhost:8080

### Get random quote
GET {{baseUrl}}/quotes HTTP/1.1

### Get random quote and translate to another language
GET {{baseUrl}}/quotes?lang=id HTTP/1.1

### Get quote by id
GET {{baseUrl}}/quotes/1 HTTP/1.1

### Get quote by id and translate to another language
GET {{baseUrl}}/quotes/1?lang=id HTTP/1.1

### Get random images
GET {{baseUrl}}/images HTTP/1.1
